
version: "3.0"

services:
  pg-db:
    container_name: pg-db
    image: postgres:13.4
    volumes:
      - ./pg:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
     - "5432:5432"
    restart: always